import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,GoogleAuthProvider,sendPasswordResetEmail,sendEmailVerification,updateProfile,signOut} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import {getFirestore,doc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyC-i4sZ1turJ4dn5XSr6cyD2ecRWHbZ4ro',authDomain:'clonity.firebaseapp.com',projectId:'clonity',storageBucket:'clonity.firebasestorage.app',messagingSenderId:'330090397428',appId:'1:330090397428:web:99b6bc0ef15d519141a8a1'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),google=new GoogleAuthProvider();
let currentUser=null;
const saveProfile=(user,data)=>setDoc(doc(db,'users',user.uid),data,{merge:true}).catch(()=>null);
const S={step:1,name:'',type:'Creativo',values:['Curiosità','Ambizione','Lealtà'],energy:72,creativity:88,photo:'',clone:''};
const TYPES=[['Esploratore','↗','Curioso, aperto, sempre in movimento.'],['Stratega','⌁','Analitico, lucido, orientato al risultato.'],['Creativo','✦','Originale, intuitivo, fuori dagli schemi.'],['Empatico','♡','Sensibile, sociale, attento alle persone.']],VALUES=['Libertà','Famiglia','Ambizione','Lealtà','Curiosità','Stabilità','Creatività','Successo'];
function openCreator(){if(!currentUser){openAuth('register');return}if(!currentUser.emailVerified){openVerify();return}S.step=1;document.body.style.overflow='hidden';render()}
function closeCreator(){document.querySelector('.creator-overlay')?.remove();document.body.style.overflow=''}
function render(){document.querySelector('.creator-overlay')?.remove();let c='';
if(S.step===1)c=`<div class="creator-step"><div class="step-copy"><span>PASSAGGIO 01</span><h2>Come ti chiami?</h2><p>È il primo dettaglio che il clone imparerà di te. Potrai scegliere un nome diverso per lui più avanti.</p></div><div class="step-form"><label>IL TUO NOME</label><input autofocus value="${S.name}" placeholder="Es. Alex"><div class="privacy-note"><b>● PRIVATO</b><p>Sei tu a decidere quali informazioni il clone potrà condividere.</p></div></div></div>`;
if(S.step===2)c=`<div class="creator-step photo-step"><div class="step-copy"><span>PASSAGGIO 02 · VOLTO</span><h2>Diamo un volto al tuo clone.</h2><p>Scatta una fotografia adesso oppure scegline una dalla galleria. Cerca una foto frontale, luminosa e senza occhiali.</p><div class="photo-safety">🔒 La fotografia resta sul dispositivo durante questa demo.</div></div><div class="photo-studio"><label class="${S.photo?'upload-zone has-photo':'upload-zone'}"><input class="photo-input" type="file" accept="image/*" capture="user">${S.photo?`<img src="${S.photo}" alt="Foto scelta">`:`<i>＋</i><strong>Scatta o scegli una foto</strong><small>JPG, PNG · volto frontale</small>`}<span>${S.photo?'CAMBIA FOTO':'APRI FOTOCAMERA / GALLERIA'}</span></label>${S.photo?'<div class="photo-checks"><span>✓ Volto rilevato</span><span>✓ Luce sufficiente</span><span>✓ Pronto per il clone</span></div>':''}</div></div>`;
if(S.step===3)c=`<div class="creator-step visual-step"><div class="step-copy"><span>PASSAGGIO 03 · GENERAZIONE VISIVA</span><h2>Nasce il tuo doppio digitale.</h2><p>Clonity conserva i tratti riconoscibili del viso e li trasforma in uno stile realistico-editoriale.</p><button class="generate-button">${S.clone?'Rigenera il clone ✦':'Genera il clone visivo ✦'}</button><small class="demo-label">DEMO: elaborazione grafica locale. La versione finale userà un modello AI dedicato.</small></div><div class="visual-lab"><div class="visual-half"><span>ORIGINALE</span><img src="${S.photo}" alt="Originale"></div><div class="morph-arrow">→</div><div class="visual-half clone"><span>IL TUO CLONE</span>${S.clone?`<img src="${S.clone}" alt="Clone">`:'<div class="empty-face">✦</div>'}</div></div></div>`;
if(S.step===4)c=`<div class="creator-step"><div class="step-copy"><span>PASSAGGIO 04 · PERSONALITÀ</span><h2>Quale energia ti rappresenta?</h2><p>Scegli l’archetipo più vicino a te. Sarà il primo punto da cui il clone inizierà a conoscerti.</p></div><div class="type-grid">${TYPES.map(t=>`<button data-type="${t[0]}" class="${S.type===t[0]?'selected':''}"><i>${t[1]}</i><strong>${t[0]}</strong><small>${t[2]}</small></button>`).join('')}</div></div>`;
if(S.step===5)c=`<div class="creator-step"><div class="step-copy"><span>PASSAGGIO 05 · IDENTITÀ</span><h2>Cosa conta davvero per te?</h2><p>Scegli fino a quattro valori. Poi regola i primi tratti: ogni giorno il clone diventerà più preciso.</p></div><div><div class="values-grid compact">${VALUES.map(v=>`<button data-value="${v}" class="${S.values.includes(v)?'selected':''}"><span>${S.values.includes(v)?'✓':'+'}</span>${v}</button>`).join('')}</div><div class="sliders compact"><label><span>ENERGIA SOCIALE <b>${S.energy}%</b></span><input data-range="energy" type="range" value="${S.energy}"></label><label><span>CREATIVITÀ <b>${S.creativity}%</b></span><input data-range="creativity" type="range" value="${S.creativity}"></label></div></div></div>`;
if(S.step===6)c=`<div class="clone-result"><div class="generated-avatar"><div class="avatar-rings"><i></i><i></i></div>${S.clone?`<img class="final-clone-photo" src="${S.clone}" alt="Clone generato">`:`<div class="avatar-face">${(S.name.slice(0,2)||'YU').toUpperCase()}</div>`}<span>CLONE ONLINE · VERSIONE 0.1</span></div><div class="result-copy"><span>IDENTITÀ GENERATA</span><h2>Ciao ${S.name||'umano'}.<br>Io sono il tuo primo clone.</h2><p>Ho già il tuo volto digitale, conosco il tuo archetipo <b>${S.type}</b> e i valori da cui partire.</p><div class="result-stats"><div><b>31%</b><small>IDENTITY SYNC</small></div><div><b>${S.values.length}</b><small>VALORI APPRESI</small></div><div><b>01</b><small>GIORNO DI VITA</small></div></div><button class="training">Prima domanda: una serata libera, amici o progetto personale? <span>Rispondi →</span></button></div></div>`;
const o=document.createElement('div');o.className='creator-overlay';o.innerHTML=`<div class="creator-shell"><header><a class="logo"><b>C</b><span>clonity</span></a><div class="progress"><span>CREAZIONE CLONE</span><div>${[1,2,3,4,5,6].map(n=>`<i class="${n<=S.step?'active':''}"></i>`).join('')}</div><small>${S.step}/6</small></div><button class="close">×</button></header>${c}<footer><button class="back">${S.step===1?'Esci':'← Indietro'}</button>${S.step<6?'<button class="next">Continua <span>→</span></button>':'<button class="next">Entra in Clonity <span>→</span></button>'}</footer></div>`;document.body.appendChild(o);bind()}
function bind(){document.querySelector('.close').onclick=closeCreator;document.querySelector('.back').onclick=()=>S.step===1?closeCreator():(S.step--,render());const n=document.querySelector('.step-form input');if(n)n.oninput=e=>{S.name=e.target.value;valid()};const p=document.querySelector('.photo-input');if(p)p.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader;r.onload=()=>{S.photo=String(r.result);S.clone='';render()};r.readAsDataURL(f)};document.querySelector('.generate-button')?.addEventListener('click',generate);document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{S.type=b.dataset.type;render()});document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{const v=b.dataset.value;S.values=S.values.includes(v)?S.values.filter(x=>x!==v):S.values.length<4?[...S.values,v]:S.values;render()});document.querySelectorAll('[data-range]').forEach(r=>r.oninput=()=>{S[r.dataset.range]=r.value;r.closest('label').querySelector('b').textContent=r.value+'%'});document.querySelector('.next').onclick=()=>S.step===6?closeCreator():(S.step++,render());document.querySelector('.training')?.addEventListener('click',e=>e.currentTarget.outerHTML='<div class="trained">✓ Prima memoria salvata. Il tuo clone è già un po’ più simile a te.</div>');valid()}
function valid(){const b=document.querySelector('.next');if(b)b.disabled=(S.step===1&&!S.name.trim())||(S.step===2&&!S.photo)||(S.step===3&&!S.clone)}
function generate(){const lab=document.querySelector('.visual-lab');lab.classList.add('generating');lab.insertAdjacentHTML('beforeend','<div class="scan-overlay"><i></i><b>CREAZIONE IDENTITÀ VISIVA</b></div>');const img=new Image;img.onload=()=>{const c=document.createElement('canvas');c.width=720;c.height=900;const x=c.getContext('2d'),z=Math.max(c.width/img.width,c.height/img.height);x.drawImage(img,(c.width-img.width*z)/2,(c.height-img.height*z)/2,img.width*z,img.height*z);x.globalCompositeOperation='color';const g=x.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,'#1748ff');g.addColorStop(.52,'#7a65ff');g.addColorStop(1,'#ff5d45');x.fillStyle=g;x.globalAlpha=.48;x.fillRect(0,0,c.width,c.height);x.globalCompositeOperation='screen';x.globalAlpha=.18;for(let y=0;y<c.height;y+=9){x.fillStyle=y%18===0?'#fff':'#1748ff';x.fillRect(0,y,c.width,1)}setTimeout(()=>{S.clone=c.toDataURL('image/jpeg',.9);render()},1100)};img.src=S.photo}
function authMessage(code){return ({'auth/email-already-in-use':'Esiste già un account con questa email.','auth/invalid-credential':'Email o password non corretti.','auth/weak-password':'La password deve contenere almeno 6 caratteri.','auth/invalid-email':'Inserisci un indirizzo email valido.','auth/popup-closed-by-user':'Accesso con Google annullato.'})[code]||'Qualcosa non ha funzionato. Riprova tra poco.'}
function shell(content){document.querySelector('.auth-overlay')?.remove();const o=document.createElement('div');o.className='auth-overlay';o.innerHTML=`<div class="auth-card"><button class="auth-close" aria-label="Chiudi">×</button><a class="logo"><b>C</b><span>clonity</span></a>${content}</div>`;document.body.appendChild(o);document.body.style.overflow='hidden';o.querySelector('.auth-close').onclick=()=>{o.remove();document.body.style.overflow=''};return o}
function openAuth(mode='login'){
 const register=mode==='register',o=shell(`<div class="auth-heading"><span>${register?'NUOVA IDENTITÀ':'BENTORNATO'}</span><h2>${register?'Crea il tuo account.':'Continua la tua storia.'}</h2><p>${register?'Prima nasce il tuo profilo. Poi potrai creare e allenare il clone.':'Accedi per ritrovare il tuo clone e continuare ad allenarlo.'}</p></div><button class="google-auth"><b>G</b> Continua con Google</button><div class="auth-divider"><i></i><span>oppure con email</span><i></i></div><form class="auth-form">${register?'<label>NOME<input name="name" autocomplete="name" required placeholder="Il tuo nome"></label>':''}<label>EMAIL<input name="email" type="email" autocomplete="email" required placeholder="nome@email.it"></label><label>PASSWORD<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="6" required placeholder="Almeno 6 caratteri"></label>${register?'<label class="terms"><input name="terms" type="checkbox" required><span>Accetto i Termini e la Privacy Policy di Clonity.</span></label>':''}<div class="auth-error" role="alert"></div><button class="auth-submit" type="submit">${register?'Crea account':'Accedi'} <span>→</span></button></form>${!register?'<button class="forgot">Password dimenticata?</button>':''}<p class="auth-switch">${register?'Hai già un account?':'Non hai ancora un account?'} <button>${register?'Accedi':'Registrati'}</button></p>`);
 const error=o.querySelector('.auth-error'),form=o.querySelector('form'),busy=v=>{o.querySelectorAll('button,input').forEach(x=>x.disabled=v)};
 o.querySelector('.auth-switch button').onclick=()=>openAuth(register?'login':'register');
 o.querySelector('.forgot')?.addEventListener('click',()=>openReset());
 o.querySelector('.google-auth').onclick=async()=>{try{busy(true);const {user}=await signInWithPopup(auth,google);currentUser=user;await saveProfile(user,{displayName:user.displayName||'',email:user.email||'',updatedAt:serverTimestamp()});o.remove();document.body.style.overflow='';openDashboard()}catch(e){busy(false);error.textContent=authMessage(e.code)}};
 form.onsubmit=async e=>{e.preventDefault();error.textContent='';const f=new FormData(form);try{busy(true);if(register){const {user}=await createUserWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')));currentUser=user;await updateProfile(user,{displayName:String(f.get('name'))});await saveProfile(user,{displayName:String(f.get('name')),email:user.email,cloneCreated:false,createdAt:serverTimestamp()});await sendEmailVerification(user);o.remove();openVerify()}else{const {user}=await signInWithEmailAndPassword(auth,String(f.get('email')),String(f.get('password')));currentUser=user;o.remove();document.body.style.overflow='';openDashboard()}}catch(err){busy(false);error.textContent=authMessage(err.code)}};
}
function openReset(){const o=shell(`<div class="auth-heading"><span>RECUPERO ACCOUNT</span><h2>Reimposta la password.</h2><p>Ti invieremo un link sicuro all’indirizzo usato per Clonity.</p></div><form class="auth-form"><label>EMAIL<input name="email" type="email" required placeholder="nome@email.it"></label><div class="auth-error"></div><button class="auth-submit">Invia il link <span>→</span></button></form><p class="auth-switch"><button>← Torna al login</button></p>`);o.querySelector('.auth-switch button').onclick=()=>openAuth('login');o.querySelector('form').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{await sendPasswordResetEmail(auth,String(email));o.querySelector('.auth-heading').innerHTML='<span>EMAIL INVIATA</span><h2>Controlla la posta.</h2><p>Se l’indirizzo è registrato, troverai il link per scegliere una nuova password.</p>';e.currentTarget.remove()}catch(err){o.querySelector('.auth-error').textContent=authMessage(err.code)}}}
function openVerify(){const o=shell(`<div class="verify-icon">✉</div><div class="auth-heading center"><span>ULTIMO PASSAGGIO</span><h2>Verifica la tua email.</h2><p>Abbiamo inviato il link a <b>${currentUser?.email||'la tua email'}</b>. Dopo il click torna qui.</p></div><button class="auth-submit verify-check">Ho verificato l’email <span>→</span></button><button class="verify-resend">Invia di nuovo</button><div class="auth-error center"></div>`);o.querySelector('.verify-check').onclick=async()=>{await auth.currentUser?.reload();currentUser=auth.currentUser;if(currentUser?.emailVerified){o.remove();document.body.style.overflow='';openDashboard()}else{o.querySelector('.auth-error').textContent='Non risulta ancora verificata. Controlla anche lo spam.'}};o.querySelector('.verify-resend').onclick=async()=>{await sendEmailVerification(auth.currentUser);o.querySelector('.auth-error').textContent='Nuova email inviata.'}}
function openDashboard(){if(!currentUser)return openAuth('login');document.querySelector('.dashboard-overlay')?.remove();const name=currentUser.displayName||currentUser.email?.split('@')[0]||'umano',o=document.createElement('div');o.className='dashboard-overlay';o.innerHTML=`<div class="dashboard"><header><a class="logo"><b>C</b><span>clonity</span></a><div class="dash-user"><span>${name.slice(0,2).toUpperCase()}</span><div><b>${name}</b><small>${currentUser.email}</small></div><button class="dash-close">×</button></div></header><main><div class="dash-kicker">IL TUO SPAZIO PRIVATO</div><h1>Ciao, ${name}.<br><em>Il tuo altro te ti aspetta.</em></h1><div class="dash-grid"><section class="clone-empty"><div class="clone-orbit"><i></i><b>?</b></div><span>CLONE NON ANCORA CREATO</span><h2>Qui inizierà la tua seconda identità.</h2><p>Volto, personalità, valori e prime memorie: costruiremo il tuo clone insieme, un passaggio alla volta.</p><button class="dash-create">Crea il mio primo clone <b>→</b></button></section><aside><span>PROFILO UMANO</span><strong>${currentUser.emailVerified?'✓ Email verificata':'! Email da verificare'}</strong><div><b>0%</b><small>IDENTITY SYNC</small></div><button class="dash-logout">Esci dall’account</button></aside></div></main></div>`;document.body.appendChild(o);document.body.style.overflow='hidden';o.querySelector('.dash-close').onclick=()=>{o.remove();document.body.style.overflow=''};o.querySelector('.dash-create').onclick=()=>{o.remove();openCreator()};o.querySelector('.dash-logout').onclick=async()=>{await signOut(auth);o.remove();document.body.style.overflow=''}}
function renderAccount(){document.querySelector('.account-actions')?.remove();const nav=document.querySelector('.header nav');if(!nav)return;const box=document.createElement('div');box.className='account-actions';box.innerHTML=currentUser?`<button class="account-pill"><i>${(currentUser.displayName||currentUser.email||'U').slice(0,2).toUpperCase()}</i><span>Il mio spazio</span></button>`:`<button class="login-link">Accedi</button><button class="register-link">Registrati</button>`;nav.appendChild(box);box.querySelector('.login-link')?.addEventListener('click',()=>openAuth('login'));box.querySelector('.register-link')?.addEventListener('click',()=>openAuth('register'));box.querySelector('.account-pill')?.addEventListener('click',openDashboard)}
onAuthStateChanged(auth,user=>{currentUser=user;renderAccount()});
document.querySelectorAll('button').forEach(b=>{if(/prova|crea|inizia/i.test(b.textContent))b.addEventListener('click',openCreator)});document.querySelector('.hamb')?.addEventListener('click',()=>document.querySelector('.header nav').classList.toggle('open'));
